pipeline {
    agent any
  
    stages {
        stage('Preparation') {
            steps {
                echo 'Doing nothing in preparation..'
            }
        }
        
        stage('Build') {
            agent {
                docker {
                    image 'maven:3.6.0-jdk-8-alpine'
                    reuseNode true
                }
            }    
            steps{
                sh 'pwd'
                echo 'Starting Build stage...'
                echo 'Compiling, testing and building...'
                sh 'mvn clean install'
            }     

        }
        
        stage('Results'){
            steps{
                echo 'Starting Results stage...'
                junit '**/target/surefire-reports/TEST-*.xml'
                archiveArtifacts '**/target/*.jar'    
            }
        }
        
    }

    post { 
        always {
            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}