pipeline {
    agent any
    //Testing webhook 1
    stages {
        stage('Preparation') {
            steps {
                echo 'Doing nothing in preparation..'
            }
        }
        
        stage('Build') {
            environment {
                JOB_PATH = 'jenkins/jobs/develop_build_job/'
                MAVEN_SETTINGS = 'mvn-settings.xml'
            }    

            agent {
                docker {
                    image 'maven:3.6.0-jdk-8-alpine'
                    args '-p 8086:8086'
                    reuseNode true
                }
            }    
            steps{
                sh 'pwd'
                echo 'Starting Build stage...'
                echo 'Compiling, testing and building...'
                sh 'mvn --settings ${JOB_PATH}${MAVEN_SETTINGS} clean install'
            }     

        }
        
        stage('Results'){
            steps{
                echo 'Starting Results stage...'
                junit '**/target/surefire-reports/TEST-*.xml'
                archiveArtifacts '**/target/*.jar'    
            }
        }
        
    }

    post { 
        always {
            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}