pipeline {
    agent any
    //Testing webhook
    stages {
        stage('Preparation') {
            steps {
                echo 'Doing nothing in preparation..'
            }
        }
        
        stage('Build') {
            environment {
                JOB_PATH = 'jenkins/jobs/develop_build_job'
                MAVEN_SETTINGS = 'mvn-settings.xml'
            }    

            agent {
                docker {
                    image 'maven:3.6.0-jdk-8-alpine'
                    reuseNode true
                }
            }    
            steps{
                dir(JOB_PATH){
                    sh 'pwd'
                    echo 'Starting Build stage...'
                    echo 'Compiling, testing and building...'
                    sh 'mvn --settings ${MAVEN_SETTINGS} clean install'
                }
            }     

        }
        
        stage('Results'){
            steps{
                echo 'Starting Results stage...'
                junit '**/target/surefire-reports/TEST-*.xml'
                archiveArtifacts '**/target/*.jar'    
            }
        }
        
    }

    post { 
        always {
            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}