pipeline {
  agent any

  environment{
    JDK_PATH = tool name: 'Java 8_152'
    JAVA_HOME = "${JDK_PATH}"
    MAVEN_DOCKER_IMAGE = 'maven:3.6-jdk-8'
  }

  stages{
    stage('Print params'){
      steps{
        echo "DEVELOPMENT_VERSION ${params.DEVELOPMENT_VERSION}"
        echo "RELEASE_VERSION ${params.RELEASE_VERSION}"
        echo "DRY_RUN ${params.DRY_RUN}"
        echo "CONFIG_FILE_ID ${params.CONFIG_FILE_ID}"
        echo "GIT_USER_NAME ${params.GIT_USER_NAME}"
        echo "GIT_USER_EMAIL ${params.GIT_USER_EMAIL}"

      }
    }
    stage('Preparation'){
      steps{
        sh "git config user.name ${params.GIT_USER_NAME}"
        sh "git config user.email ${params.GIT_USER_EMAIL}"
        echo 'getReleaseVersion: ' + getReleaseVersion(false)
      }
    }    
  }
}

def getReleaseVersion(boolean isRelease) {
    def version = readMavenPom().getVersion()
    echo version
 
    if(isRelease){
        if(version.contains("-RC")){
            return version.substring(0, version.indexOf("-RC"))
        }
    } else {
        if(!version.contains("-RC")){
            return version.replace("-SNAPSHOT", "")+"-RC1";
        }
    }
    return version.replace("-SNAPSHOT", "")
}
