pipeline {
    agent any
    environment{
        CONFIG_FILE_ID = 'byggReleaseConfig'
        MAVEN_IMAGE = 'maven:3.6-jdk-8'
    }

    stages {
        stage('Build') {
            agent {
                docker {
                    image "${MAVEN_IMAGE}"
                    reuseNode true
                }
            }
            steps {
                echo 'Starting Build stage...'
                configFileProvider([configFile(fileId: "${CONFIG_FILE_ID}", variable: 'MAVEN_SETTINGS')]) {
                    sh 'pwd'
                    echo 'Compiling, testing and building...'
                    sh 'mvn --global-settings ${MAVEN_SETTINGS} clean install'
                }
            }     
        }        
    }

    post {
        always {
            echo 'Starting results handling...'
            junit '**/target/surefire-reports/TEST-*.xml'
            jacoco()
            archiveArtifacts '**/target/*.jar'
        }

        unsuccessful {
            echo 'Build unsuccessful'
        }

        changed {
            script {
                if ("${currentBuild.currentResult}" == 'SUCCESS') {
                    echo "Current build successful, previous build was unsuccessful"
                }
            }
        }

        cleanup {
            echo 'Cleaning workspace...'
            cleanWs()
        }
    }
}